### ISSUE TITLE
Remove ROMs

### ISSUE THREAD

**Issue by gpadd** [Tko1/HaskBoy#1]
You can add a .gitignore file with *.gbc and *.gb (along with other things you do not want ending up in the git repo)to not allow the ROMs to get into the project. You might want to remove them completely from the git repo, as it is illegal to distribute ROMs..
Cool project, I hope you'll keep working on it :-) 👍

**Comment by Tko1** [comment]
Hey thanks!  The files have been removed and their extensions added to a .gitignore.   I actually have continued working on the project, but in Clojure instead.   I have a feeling that might interest you as well, I will be sure to get that up on here in a bit!
